version: "3.9"

volumes:
  ft-db-volume:
    name: ft-db-volume

networks:
  ft-network:
    name: ft-network

services:
  bot:
    container_name: ft-bot
    build: .
    depends_on:
      - db
    env_file:
      - .env
    tty: true
    restart: always
    networks:
      - ft-network

  db:
    container_name: ft-db
    image: postgres:15.0-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    healthcheck:
      test: pg_isready --username=${POSTGRES_USER} --dbname=${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ft-db-volume:/var/lib/postgresql/data
      - ./deploy/postgres:/docker-entrypoint-initdb.d
    networks:
      - ft-network
